reviewOne
Joel-leal/cronometro pull request #2
Opened 2021-04-12 16:19 UTC by Joel-leal

Algumas alterações ainda precisam ser feitas no exercício.

2021-04-12 17:28 UTC, marco-souza requested changes

2021-04-12 17:28 UTC, marco-souza commented on funcCronometro.js
> +    const root = document.getElementById("corpo");
É uma boa prática manter tudo que for código em inglês

2021-04-12 17:28 UTC, marco-souza commented on funcCronometro.js
> +    document.getElementById("divOne").style.display = "none"; // ocultando a divOne quanto o contador
Outra prática é colocar ífem entre as palavras dos ids, como por exemplo `div-one` no lugar de `divOne`.

2021-04-12 17:28 UTC, marco-souza commented on funcCronometro.js
> +      document.getElementById("divTwo").remove(); //remover a div divTow quando o contador acabar de contar.
O mesmo aqui. Além disso, temos que dar uma melhorada na identação. Note que esta linha está começando na mesma linha do if, só que isso é interno ao if.

como regra geral, a linha seguinte a um `{`, `[` ou `(`, aumenta sua identação em +1.

2021-04-13 16:26 UTC, merged

2021-04-13 16:26 UTC, Joel-leal commented on funcCronometro.js
> +    document.getElementById("divOne").style.display = "none"; // ocultando a divOne quanto o contador
Posso alterar tudo para o modelo div-one?

2021-04-13 16:26 UTC, Joel-leal commented on funcCronometro.js
> +      document.getElementById("divTwo").remove(); //remover a div divTow quando o contador acabar de contar.
ok!

2021-04-13 16:28 UTC, marco-souza commented
Pode mergear não doido, só podemos mergear depois de resolver os comentários